name: Hello World Repo Dispatch
on:
  repository_dispatch:
    types: my-event

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: echo ${{ github.event.client_payload.foo }}
